version: '3.8'

services:
  slack-channel-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_MODE=http
      - PORT=3000
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_URL=${LLM_API_URL}
      - ALLOWED_CHANNEL_IDS=${ALLOWED_CHANNEL_IDS}
      - ALLOW_ALL_PUBLIC_CHANNELS=${ALLOW_ALL_PUBLIC_CHANNELS}
      - ALLOW_PRIVATE_CHANNELS=${ALLOW_PRIVATE_CHANNELS}
    restart: unless-stopped 